name: Build & Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  permissions:
    contents: write
  build_binaries:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      NAME: ncr-tool
      DESC: "ncr-mirror cli tools"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Version
        id: prep
        env:
          REF: ${{ inputs.tag }}
        run: |
          tag=${{ inputs.tag }}
          version=$(echo $tag | sed 's/v//g')
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Binaries
        id: build
        shell: bash
        run: |
          mkdir ncr-tool-binaries
          
          foreach ($arch in @('amd64', 'arm64')) {
            $env:GOARCH = $arch
            $filename = linux-$arch
            go build -o ncr-tool-binaries/ncr-tool-${filename}_${env:VERSION} -ldflags="-extldflags -static" -trimpath
          }
          
          foreach ($arch in @('amd64', 'arm64')) {
            $env:GOOS = 'windows'
            $env:GOARCH = $arch
            $filename = windows-$arch
            go build -o ncr-tool-binaries/ncr-tool-${filename}_${env:VERSION}.exe -ldflags="-extldflags -static" -trimpath
          }
          
          foreach ($arch in @('amd64', 'arm64')) {
            $env:GOOS = 'darwin'
            $env:GOARCH = $arch
            $filename = darwin-$arch
            go build -o ncr-tool-binaries/ncr-tool-${filename}_${env:VERSION} -ldflags="-extldflags -static" -trimpath
          }

      - name: Upload Artifact
        uses: nanoufo/action-upload-artifacts-and-release-assets@v2
        with:
          path: |
            ncr-tool-binaries/*

      - name: Move Files to Release Directory
        shell: bash
        run: |
          mkdir -p release

          for file in $(ls builds | grep -E "^ncr-tool"); do
            mv ncr-tool-binaries/$file/$file release/
          done

          for file in $(ls release); do
            sha256sum release/$file | awk '{print $1}' > release/$file.sha256.txt
          done

          ls -l release/

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            release/*